-- ── INVOICES FOR MISSED APPOINTMENTS ──
-- NOT YET APPLIED — run after 0001-0011.
--
-- The salon does not store card details and does not want to. A missed or
-- late-cancelled appointment produces an invoice instead: an email with the
-- amount, a reference, and a way to pay it.
--
-- DELIBERATELY PROVIDER-AGNOSTIC
-- Written so it works before any payment provider exists. Today the email can
-- carry a Vipps number and a reference, the client pays in ten seconds, and
-- whoever sees the money marks it paid here. When a hosted checkout is set up
-- later, pay_url is filled in and the same email grows a button — nothing else
-- in this file changes, and no invoice already sent becomes wrong.
--
-- WHAT THIS DOES NOT DO
-- It does not guarantee payment, and nothing built without holding money or a
-- card ever could. It makes paying easy and being chased polite, which is what
-- actually gets most invoices settled.

create table invoices (
  id uuid primary key default gen_random_uuid(),

  -- Sequential and human-readable, because "invoice 14" is what gets said on
  -- the phone. Not the primary key: an accounting number must never change if
  -- a row is moved or restored.
  number int generated by default as identity,

  booking_id uuid not null references bookings(id) on delete cascade,

  -- Copied, not joined. An invoice is a record of what was sent at the time —
  -- if the service is renamed or repriced later, the invoice must still say
  -- what the client was actually told.
  customer_name text not null,
  customer_email text,
  customer_phone text not null,
  service_name text not null,
  appointment_date date not null,
  appointment_time time not null,

  reason text not null check (reason in ('no_show', 'late_cancellation')),
  amount numeric(10,2) not null check (amount > 0),

  -- Filled in once a hosted checkout exists. Null means the email falls back
  -- to "pay by Vipps to this number, quote this reference".
  pay_url text,

  status text not null default 'unpaid'
    check (status in ('unpaid', 'paid', 'waived', 'cancelled')),

  -- How it was settled: 'vipps', 'card', 'cash', 'in_salon', 'other'. Free
  -- text rather than an enum, because the salon will find ways nobody planned.
  paid_method text,
  paid_at timestamptz,
  paid_note text,

  sent_at timestamptz,
  reminder_sent_at timestamptz,

  created_at timestamptz not null default now()
);

create index invoices_status_idx on invoices(status, created_at);
create index invoices_booking_idx on invoices(booking_id);

alter table invoices enable row level security;
-- No anon policy: invoices carry names, phone numbers and amounts.
create policy "admin manage invoices" on invoices for all
  using (auth.role() = 'authenticated') with check (auth.role() = 'authenticated');

-- Salon-wide payment details, so the invoice email does not hard-code them.
insert into app_settings (key, value) values ('vipps_number', '')
  on conflict (key) do nothing;
insert into app_settings (key, value) values ('invoice_due_days', '14')
  on conflict (key) do nothing;

create or replace function get_payment_settings()
returns table (vipps_number text, due_days int)
language sql stable security definer set search_path = public as $$
  select coalesce((select value from app_settings where key = 'vipps_number'), ''),
         coalesce((select value::int from app_settings where key = 'invoice_due_days'), 14);
$$;
grant execute on function get_payment_settings to anon;

-- ── RAISING ONE ──
-- Never automatic. The owner decides, exactly as with the no-show email: a
-- missed appointment usually has a reason behind it, and a machine invoicing
-- someone whose morning fell apart is how a salon loses a client it could have
-- kept.
create or replace function staff_create_invoice(p_pin text, p_booking_id uuid)
returns invoices language plpgsql security definer set search_path = public as $$
declare v_b record; v_inv invoices;
begin
  if not verify_staff_pin(p_pin) then raise exception 'Invalid PIN'; end if;

  select b.*, sv.name as service_name into v_b
  from bookings b join services sv on sv.id = b.service_id
  where b.id = p_booking_id;
  if v_b.id is null then raise exception 'Booking not found'; end if;

  if not v_b.late_cancellation and v_b.status <> 'no_show' then
    raise exception 'This booking was not missed or cancelled late, so there is nothing to invoice';
  end if;
  if v_b.cancellation_fee is null or v_b.cancellation_fee <= 0 then
    raise exception 'There is no amount to invoice - this service has no fixed price, so set the amount by hand';
  end if;
  if v_b.cancellation_fee_waived then
    raise exception 'This fee was waived';
  end if;
  if exists (select 1 from invoices i where i.booking_id = p_booking_id
             and i.status in ('unpaid', 'paid')) then
    raise exception 'An invoice already exists for this booking';
  end if;

  insert into invoices (
    booking_id, customer_name, customer_email, customer_phone,
    service_name, appointment_date, appointment_time,
    reason, amount
  ) values (
    v_b.id, v_b.customer_name, v_b.customer_email, v_b.customer_phone,
    v_b.service_name, v_b.date, v_b.start_time,
    case when v_b.status = 'no_show' then 'no_show' else 'late_cancellation' end,
    v_b.cancellation_fee
  ) returning * into v_inv;

  return v_inv;
end; $$;
grant execute on function staff_create_invoice to anon;

-- An amount typed by hand, for the services priced "from" where no half exists
-- until someone decides it.
create or replace function staff_create_invoice_manual(
  p_pin text, p_booking_id uuid, p_amount numeric
) returns invoices language plpgsql security definer set search_path = public as $$
declare v_b record; v_inv invoices;
begin
  if not verify_staff_pin(p_pin) then raise exception 'Invalid PIN'; end if;
  if p_amount is null or p_amount <= 0 then raise exception 'Enter an amount'; end if;

  select b.*, sv.name as service_name into v_b
  from bookings b join services sv on sv.id = b.service_id
  where b.id = p_booking_id;
  if v_b.id is null then raise exception 'Booking not found'; end if;

  insert into invoices (
    booking_id, customer_name, customer_email, customer_phone,
    service_name, appointment_date, appointment_time, reason, amount
  ) values (
    v_b.id, v_b.customer_name, v_b.customer_email, v_b.customer_phone,
    v_b.service_name, v_b.date, v_b.start_time,
    case when v_b.status = 'no_show' then 'no_show' else 'late_cancellation' end,
    p_amount
  ) returning * into v_inv;

  update bookings set cancellation_fee = p_amount where id = p_booking_id;
  return v_inv;
end; $$;
grant execute on function staff_create_invoice_manual to anon;

create or replace function staff_mark_invoice_sent(p_pin text, p_id uuid)
returns void language plpgsql security definer set search_path = public as $$
begin
  if not verify_staff_pin(p_pin) then raise exception 'Invalid PIN'; end if;
  update invoices set sent_at = coalesce(sent_at, now()) where id = p_id;
end; $$;
grant execute on function staff_mark_invoice_sent to anon;

-- Marked by whoever sees the money — the person at the till, not the owner
-- later. Also writes it back to the booking so the reports agree.
create or replace function staff_mark_invoice_paid(
  p_pin text, p_id uuid, p_method text, p_note text default null
) returns void language plpgsql security definer set search_path = public as $$
declare v_booking uuid;
begin
  if not verify_staff_pin(p_pin) then raise exception 'Invalid PIN'; end if;
  update invoices set
    status = 'paid', paid_at = now(),
    paid_method = nullif(trim(coalesce(p_method, '')), ''),
    paid_note = nullif(trim(coalesce(p_note, '')), '')
  where id = p_id and status = 'unpaid'
  returning booking_id into v_booking;
  if v_booking is null then raise exception 'That invoice is not waiting to be paid'; end if;

  update bookings set
    cancellation_fee_settled = true,
    cancellation_fee_settled_at = now()
  where id = v_booking;
end; $$;
grant execute on function staff_mark_invoice_paid to anon;

create or replace function staff_waive_invoice(p_pin text, p_id uuid, p_note text default null)
returns void language plpgsql security definer set search_path = public as $$
declare v_booking uuid;
begin
  if not verify_staff_pin(p_pin) then raise exception 'Invalid PIN'; end if;
  update invoices set status = 'waived', paid_note = nullif(trim(coalesce(p_note, '')), '')
  where id = p_id and status = 'unpaid'
  returning booking_id into v_booking;
  if v_booking is not null then
    update bookings set cancellation_fee_waived = true where id = v_booking;
  end if;
end; $$;
grant execute on function staff_waive_invoice to anon;

-- ── THE LIST ──
-- Unpaid first and oldest first, because an invoice nobody has looked at for
-- three weeks is the one that needs a phone call.
create or replace function staff_invoices(p_pin text, p_status text default null)
returns table (
  id uuid,
  number int,
  booking_id uuid,
  customer_name text, customer_email text, customer_phone text,
  service_name text,
  appointment_date date, appointment_time time,
  reason text,
  amount numeric,
  status text,
  pay_url text,
  sent_at timestamptz,
  reminder_sent_at timestamptz,
  paid_at timestamptz, paid_method text,
  days_outstanding int
) language plpgsql security definer set search_path = public as $$
begin
  if not verify_staff_pin(p_pin) then raise exception 'Invalid PIN'; end if;
  return query
  select i.id, i.number, i.booking_id,
         i.customer_name, i.customer_email, i.customer_phone,
         i.service_name, i.appointment_date, i.appointment_time,
         i.reason, i.amount, i.status, i.pay_url,
         i.sent_at, i.reminder_sent_at, i.paid_at, i.paid_method,
         case when i.status = 'unpaid' and i.sent_at is not null
              then (((now() at time zone 'Europe/Oslo')::date - i.sent_at::date))::int
              else null end
  from invoices i
  where p_status is null or i.status = p_status
  order by
    case i.status when 'unpaid' then 0 else 1 end,
    i.created_at;
end; $$;
grant execute on function staff_invoices to anon;

-- What the year looks like: raised, collected, written off. The number that
-- says whether the policy is working, and whether chasing is worth the time.
create or replace function admin_invoice_summary(p_pin text, p_from date, p_to date)
returns table (
  raised int, raised_total numeric,
  paid int, paid_total numeric,
  waived int, waived_total numeric,
  unpaid int, unpaid_total numeric,
  collection_rate numeric
) language plpgsql security definer set search_path = public as $$
begin
  if not is_owner_pin(p_pin) then raise exception 'Invalid owner PIN'; end if;
  return query
  select count(*)::int,
         coalesce(sum(i.amount), 0),
         count(*) filter (where i.status = 'paid')::int,
         coalesce(sum(i.amount) filter (where i.status = 'paid'), 0),
         count(*) filter (where i.status = 'waived')::int,
         coalesce(sum(i.amount) filter (where i.status = 'waived'), 0),
         count(*) filter (where i.status = 'unpaid')::int,
         coalesce(sum(i.amount) filter (where i.status = 'unpaid'), 0),
         -- Waived invoices are excluded from the denominator: the salon chose
         -- not to collect those, and counting them as failures would make a
         -- kind decision look like a bad one.
         case when count(*) filter (where i.status in ('paid', 'unpaid')) = 0 then null
              else round(
                100.0 * count(*) filter (where i.status = 'paid')
                / count(*) filter (where i.status in ('paid', 'unpaid')), 0)
         end
  from invoices i
  where (i.created_at at time zone 'Europe/Oslo')::date between p_from and p_to;
end; $$;
grant execute on function admin_invoice_summary to anon;
